apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story

  template:
    metadata:
      labels:
        app: story

    spec:
      containers:
        - name: story-app
          image: slobodang/kub-data-demo:1
          volumeMounts:
            - mountPath: /app/story
              name: story-volume-1
            - mountPath: /app/story
              name: story-volume-2
      volumes:
        - name: story-volume-1
          persistentVolumeClaim:
            claimName: host-pvc-1
        - name: story-volume-2
          persistentVolumeClaim:
            claimName: host-pvc-2

          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          # volumeMounts:
          #   - mountPath: /app
          #     name: story-volume
          # volumes:
          #   - name: story-volume
          #     emptyDir:
          #       sizeLimit: 500Mi
