apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: host-pvc-2
spec:
  volumeName: host-pv-2
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources: 
    requests:
      storage: 1Gi
